/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapasRouteImport } from './routes/mapas'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as EditorRegionIdRouteImport } from './routes/editor.$regionId'
import { Route as RutaTrailIdRouteImport } from './routes/ruta.$trailId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasRoute = MapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRegionIdRoute = EditorRegionIdRouteImport.update({
  id: '/editor/$regionId',
  path: '/editor/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RutaTrailIdRoute = RutaTrailIdRouteImport.update({
  id: '/ruta/$trailId',
  path: '/ruta/$trailId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapas': typeof MapasRoute
  '/online': typeof OnlineRoute
  '/editor/$regionId': typeof EditorRegionIdRoute
  '/ruta/$trailId': typeof RutaTrailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapas': typeof MapasRoute
  '/online': typeof OnlineRoute
  '/editor/$regionId': typeof EditorRegionIdRoute
  '/ruta/$trailId': typeof RutaTrailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapas': typeof MapasRoute
  '/online': typeof OnlineRoute
  '/editor/$regionId': typeof EditorRegionIdRoute
  '/ruta/$trailId': typeof RutaTrailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mapas' | '/online' | '/editor/$regionId' | '/ruta/$trailId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mapas' | '/online' | '/editor/$regionId' | '/ruta/$trailId'
  id:
    | '__root__'
    | '/'
    | '/mapas'
    | '/online'
    | '/editor/$regionId'
    | '/ruta/$trailId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapasRoute: typeof MapasRoute
  OnlineRoute: typeof OnlineRoute
  EditorRegionIdRoute: typeof EditorRegionIdRoute
  RutaTrailIdRoute: typeof RutaTrailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas': {
      id: '/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof MapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$regionId': {
      id: '/editor/$regionId'
      path: '/editor/$regionId'
      fullPath: '/editor/$regionId'
      preLoaderRoute: typeof EditorRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruta/$trailId': {
      id: '/ruta/$trailId'
      path: '/ruta/$trailId'
      fullPath: '/ruta/$trailId'
      preLoaderRoute: typeof RutaTrailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapasRoute: MapasRoute,
  OnlineRoute: OnlineRoute,
  EditorRegionIdRoute: EditorRegionIdRoute,
  RutaTrailIdRoute: RutaTrailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
